### ISSUE TITLE
Icon on marker doesn't work

### ISSUE THREAD

**Issue by Sogl** [finanalyst/grav-plugin-map-marker-leaflet#10]
Hello!

I use bootstrap 3 and fontawesome 4.7.
On site my icons work fine, but on map I see square (icon don't recognized).

Code:
```
[map-leaflet lat=46.994520 lng=142.728313 zoom=14 height=400px mapname=neighbourhood
style=neighbourhood scale ]
[a-markers markerColor="red" iconColor="white"]
[{ "lat": "46.994520", "lng": "142.728313", "icon": "home" } ]
[/a-markers]
[/map-leaflet]
```

My font-awesome include line in scss is `@import "~font-awesome/scss/font-awesome";`

Any ideas how to fix?

**Comment by finanalyst** [comment]
If this is still an issue, re-open

**Comment by lazybadger** [comment]
I can confirm "issue" in current 1.1.1 in _this_ form:
Icon added to map only if full icon name is used.
![ursinecorner ru](https://user-images.githubusercontent.com/859449/88493746-3d7b7300-cfcc-11ea-9f0e-632dc5d0c256.png)

While I have `"icon": "fa fa-home"` in shortcode, it shown on map, "home"|"fa-home" - no
