### ISSUE TITLE
Example not present

### ISSUE THREAD

**Issue by jeremycherfas** [finanalyst/grav-plugin-map-marker-leaflet#2]
````
### Example
The following code is in <path to grav>/user/map/default.md
````

Does not in fact exist at that location or anywhere else I can find.

**Comment by finanalyst** [comment]
Sorry, this is not as clear for a newcomer as it should be.

You will need to set up GRAV and create a directory called 03.map (assuming
you are adding to a brand new GRAV setup).

Then inside that directory create an file called default.md with the
content in the example.

When you hit GrAV you will see a tab called map. Click on that and you
should see the maps (there are two in the example)

Regards
Richard
