### ISSUE TITLE
Plugin doesn't work with autoescape on

### ISSUE THREAD

**Issue by mahagr** [finanalyst/grav-plugin-map-marker-leaflet#20]
If you turn on auto escaping on Grav (enabled by default in Gantry themes and usually new projects):

system.yaml
```
twig:
  autoescape: true
```

The plugin stops to work. This is because of you're doing the escaping in the wrong place.

All escaping should be done inside the template files using `|e` filter (read twig docs on it) when the variable is outputed (`{{ var|e }}' and if the variable should not be escaped, it should have `|raw` in it.

**Comment by finanalyst** [comment]
lazybadger provided a solution.

**Comment by mahagr** [comment]
FYI: auto-escape will be turned on in Grav 1.7 by default.
