### ISSUE TITLE
Template "@Var:" is not defined

### ISSUE THREAD

**Issue by mahagr** [finanalyst/grav-plugin-map-marker-leaflet#21]
Can be replicated if using bad shortcode:

```
[map-leaflet lat=51.505 lng=-0.09 zoom=13 mapname=neighbourhood variant=neighbourhood scale ]
[a-markers markerColor="darkblue"
iconColor="white"
]
[a-markers markerColor="beige" iconColor="darkpurple"]
```

**Comment by finanalyst** [comment]
It's not really possible to allow for all possibility of bad shortcodes. If replicates with a good shortcode, then I can see what the problem is. Otherwise, I'm closing this issue. Thanks for the attention, sorry for the delay in responding
