### ISSUE TITLE
Safe templates for all possible frontends

### ISSUE THREAD

**Issue by lazybadger** [finanalyst/grav-plugin-map-marker-leaflet#23]
v1.1.1 works without additional tricks in plain Grav.
But for using maps _in Gantry on top of Grav_ (in page content or in particles) all output must be additionally filtered with raw filter.
[partials.zip](https://github.com/finanalyst/grav-plugin-map-marker-leaflet/files/5358922/partials.zip) contains polished tested templates, only filter added to body

**Comment by finanalyst** [comment]
@lazybadger Thank you for the help. I have changed the templates for your versions. They seem OK, but I haven't tested them vigorously.

**Comment by finanalyst** [comment]
@lazybadger Also added you to Credits section.
