### ISSUE TITLE
Retina screen support

### ISSUE THREAD

**Issue by timothyarmes** [finanalyst/grav-plugin-map-marker-leaflet#3]
Can you please enable retina screen support for Thunderforest maps as explained here:

https://www.thunderforest.com/tutorials/leaflet/

You just need to add {r} to the stanza:

```
$tilestanza = "https://tile.thunderforest.com/{style}/{z}/{x}/{y}{r}.png?apikey={apikey}";
```

**Comment by finanalyst** [comment]
@timothyarmes Thank you for this.
Sorry for the delay. 
Implemented and updated.
