### ISSUE TITLE
How to display popup on a marker?

### ISSUE THREAD

**Issue by fauzie** [finanalyst/grav-plugin-map-marker-leaflet#7]
How to display marker popup like this: http://jsfiddle.net/roycode/9tw1Lpa0/1
And i want to visible default on load.

**Comment by finanalyst** [comment]
Have you tried the examples in the documentation of the plugin? 
What does 'like this' mean?   
Do you mean you don't like the marker, or you want to use extra code, or you want to use code similar to what you quoted? I do not know.
