### ISSUE TITLE
Address bar to filter location

### ISSUE THREAD

**Issue by ghtmtt** [finanalyst/grav-plugin-map-marker-leaflet#9]
Hi,

the plugin is very interesting! Do you think it is possible to add an address bar where users can type the address and the map will update to the location (AKA geocoding https://leafletjs.com/plugins.html#geocoding)?

What I'm trying to do is to add a leaflet map with your plugin in a form page of Grav, take the lat and long values (entered by the user) and send them via email together with the other values (name, surname, and other form fields).

I'm really not a php person, but I really would like to help you with this feature (if you are interested)

Thanks

**Comment by finanalyst** [comment]
@ghtmtt  Sorry for this bad delay. But your requested extra functionality is not consistent with the aims of this plugin, I'm afraid.
